### ISSUE TITLE
feed_tag generated link should use full URL

### ISSUE THREAD

**Issue by maiertech** [octopress/feeds#15]
The generated link for the page head

```
<link href='/feed/' title='Your Site Name - Posts' rel='alternate' type='application/atom+xml'>
```

should use the full URL `/feed/index.xml`. I am not sure if all feed readers are smart and add the `index.xml`. And the other reason: `html-proofer` trips over the feed URL if is says `/feed/` only throwing this error:

```
internally linking to /feed/, which does not exist (line 19)
```

**Comment by imathis** [comment]
I really don't think this should be an issue. I'm guessing the HTML proofer only expects `.html` index pages, but web servers have long known to serve up common index extensions like `.xml`. I prefer to use directory style URLs since they are cleaner to redirect if necessary and I believe this is how many blogging platforms handle RSS. If a user changes to another platform, the page may be a /feed/index.php file that generates XML. By using a directory and letting the web server direct to the index.xml file, I avoid the situation where readers will need to update their RSS subscriptions.

I'm going to close this issue, but if you can show that this is a problem beyond the proofing tool you're using, I'll look into addressing it.

**Comment by maiertech** [comment]
I had a look at the html-proofer docs. They allow only one `directory_index_file` which by default is `index.html`. It's a bit unfortunate they allow only one, not more. They allow marking any links to be marked `data-proofer-ignore` to suppress checking. Which is not an option for the generated link tag.

I opened a ticket with html-proofer: https://github.com/gjtorikian/html-proofer/issues/195

**Comment by imathis** [comment]
Thanks for the update. This tool looks pretty cool, but it definitely has it's limitations as soon as your site uses any server configuration to map urls. I'm surprised it expects you to add attributes to your site's content to ignore links. Changing the content of your site to allow proofing to pass seems icky. Some kind of external YAML config would be much better.
