### ISSUE TITLE
Entry ID format

### ISSUE THREAD

**Issue by justinrummel** [octopress/feeds#7]
Comparing my theme's generated [feed.xml](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/feed.xml) to the new Octopress feeds entry.xml, I noticed the ID has a slightly different format with hpstr having [site.url](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/feed.xml#HL22) preceding the post.id, while Octopress only has [post.id](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/feed.xml).

Any thoughts of one being better than the other?

**Comment by imathis** [comment]
Sorry, I somehow just noticed this issue. It really doesn't matter what the post.id is, so long as it is unique. In fact, it's better for it not to be a permalink since that can change, but since this isn't database driven with a place to store some kind of ID for each post, I'm not sure I can come up with anything better.
